# fly.toml app configuration file generated for sesec-backend on 2025-09-06T20:21:32+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'sesec-backend'
primary_region = 'cdg'

[build]

[deploy]
  release_command = "echo 'Deployment starting...'"

[env]
  NODE_ENV = 'production'
  PORT = '3000'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  # Health checks disabled temporarily
  # [[http_service.checks]]
  #   interval = '30s'
  #   timeout = '10s'
  #   grace_period = '30s'
  #   method = 'GET'
  #   path = '/health'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[metrics]]
  port = 9091
  path = '/metrics'
